TMP_SRC+=$(addprefix $(MODULE)/, $(SRC))
TMP_OBJ+=$(addprefix $(MODULE)/, $(OBJ))
TMP_INC+=$(addprefix $(MODULE)/, $(INC))
TMP_TST_SRC+=$(addprefix $(MODULE)/, $(TST_SRC))
TMP_TST_OBJ+=$(addprefix $(MODULE)/, $(TST_OBJ))

SRC:=$(TMP_SRC)
OBJ:=$(TMP_OBJ)
INC:=$(TMP_INC)
TST_SRC:=$(TMP_TST_SRC)
TST_OBJ:=$(TMP_TST_OBJ)
